export const DUMMY_EVENTS = [
  {
    id: 'e1',
    url: '',
    title: 'First Session with Alex Stan',
    description: 'This is a test description for meeting with Alex Stan',
    date: new Date(2022, 1, 21, 14, 30),
    guestProfile: 'https://www.facebook.com/minhquan.le.9237/',
    duration: 30,
    isMeeting: false,
  },
  {
    id: 'e2',
    url: '',
    title: 'Second Session with Alex Stan',
    description: 'This is a test description for meeting with Alex Stan',
    date: new Date(2022, 1, 21, 16, 30),
    guestProfile: 'https://www.facebook.com/minhquan.le.9237/',
    duration: 30,
    isMeeting: true,

    type: 'event',
  },
  {
    id: 'e3',
    url: '',
    title: 'First Session with Alex Stan',
    description: 'This is a test description for meeting with Alex Stan',
    date: new Date(2022, 1, 15, 9, 30),
    guestProfile: 'https://www.facebook.com/minhquan.le.9237/',
    duration: 30,
    isMeeting: false,
  },
  {
    id: 'e4',
    url: 'https://www.eventbrite.sg/e/gentle-yoga-for-terrible-times-tickets-253530525627?aff=ebdssbcitybrowse&keep_tld=1',
    title: 'Gentle Yoga for Terrible Times',
    description: 'This is a test description for meeting with Alex Stan',
    date: new Date(2022, 2, 5, 9, 30),
    guestProfile: 'https://www.facebook.com/minhquan.le.9237/',
    duration: 30,
    isMeeting: true,
  },
  {
    id: 'e5',
    url: '',
    title: 'First Session with Alex Stan',
    description: 'This is a test description for meeting with Alex Stan',
    date: new Date(2022, 0, 12, 9, 30),
    guestProfile: null,
    duration: 30,
    isMeeting: false,
  },
  {
    id: 'e6',
    url: '',
    title: 'First Session with Alex Stan',
    description: 'This is a test description for meeting with Alex Stan',
    date: new Date(2022, 1, 25, 9, 30),
    guestProfile: 'https://www.facebook.com/minhquan.le.9237/',
    duration: 30,
    isMeeting: true,
  },
  {
    id: 'e7',
    url: '',
    title: 'Third Session with Alex Stan',
    description: 'This is a test description for meeting with Alex Stan',
    date: new Date(2022, 1, 21, 9, 30),
    guestProfile: 'https://www.facebook.com/minhquan.le.9237/',
    duration: 30,
    isMeeting: false,
  },
  {
    id: 'e8',
    url: '',
    title: 'Meeting interview',
    description: 'This is a test description for meeting with Alex Stan',
    date: new Date(2022, 1, 15, 9, 30),
    guestProfile: 'https://www.facebook.com/minhquan.le.9237/',
    duration: 30,
    isMeeting: false,
  },
  {
    id: 'e9',
    url: '',
    title: 'Meeting interview',
    description: 'This is a test description for meeting with Alex Stan',
    date: new Date(2022, 1, 15, 9, 30),
    guestProfile: 'https://www.facebook.com/minhquan.le.9237/',
    duration: 30,
    isMeeting: false,
  },
  {
    id: 'e10',
    url: '',
    title: 'Meeting interview',
    description: 'This is a test description for meeting with Alex Stan',
    date: new Date(2022, 1, 20, 9, 30),
    guestProfile: null,
    duration: 30,
    isMeeting: false,
  },
]
